iFrame = 0;
prevSpd = 0;
unpaused = false;
if (!variable_instance_exists(id, "durStart")) durStart = 0;
if (!variable_instance_exists(id, "x_scale")) x_scale = 1;
if (!variable_instance_exists(id, "y_scale")) y_scale = 1;
image_xscale = x_scale;
image_yscale = y_scale;
image_speed = 0;